CREATE TABLE USERS_REAL (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(30) CHECK (role IN ('USER','REVIEWER','ADMIN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_TOKENS (
    token_id VARCHAR2(64) PRIMARY KEY,
    user_id NUMBER NOT NULL,
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active_flag CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    CONSTRAINT fk_token_user
        FOREIGN KEY (user_id)
        REFERENCES USERS_REAL(user_id)
        ON DELETE CASCADE
);

CREATE TABLE CODE_SUBMISSIONS (
    submission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id VARCHAR2(64) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    language VARCHAR2(50),
    status VARCHAR2(30) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_token
        FOREIGN KEY (token_id)
        REFERENCES USER_TOKENS(token_id)
);

CREATE TABLE REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id NUMBER NOT NULL,
    reviewer_token VARCHAR2(64) NOT NULL,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    comments CLOB,
    review_hash VARCHAR2(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_submission
        FOREIGN KEY (submission_id)
        REFERENCES CODE_SUBMISSIONS(submission_id),
    CONSTRAINT fk_review_token
        FOREIGN KEY (reviewer_token)
        REFERENCES USER_TOKENS(token_id)
);

CREATE TABLE AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_token VARCHAR2(64),
    action_type VARCHAR2(50),
    target_id NUMBER,
    encrypted_payload RAW(2000),
    hash_value VARCHAR2(64),
    previous_hash VARCHAR2(64),
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE REVIEW_ANALYSIS (
    submission_id NUMBER PRIMARY KEY,
    avg_rating NUMBER,
    rating_stddev NUMBER,
    weighted_score NUMBER,
    consensus_status VARCHAR2(30),
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_submission
        FOREIGN KEY (submission_id)
        REFERENCES CODE_SUBMISSIONS(submission_id)
);

CREATE TABLE TRUST_SCORES (
    token_id VARCHAR2(64) PRIMARY KEY,
    trust_score NUMBER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trust_token
        FOREIGN KEY (token_id)
        REFERENCES USER_TOKENS(token_id)
);

ALTER TABLE REVIEWS
ADD bias_flag VARCHAR2(10);